"""
RateMyProfessor ratings loader.

Loads pre-cached ratings from rmp_ratings.json (generated by refresh_rmp.py).
No API calls at runtime - if professor isn't in cache, returns None.
"""

import json
import re
from dataclasses import dataclass
from pathlib import Path

from src.utils.logger import setup_logger

logger = setup_logger(__name__)

# Cache file location
RATINGS_FILE = Path(__file__).parent / "data" / "rmp_ratings.json"


@dataclass
class ProfessorRating:
    """Professor rating data from RateMyProfessor."""
    name: str
    rating: float | None         # 1.0-5.0, None if not found
    num_ratings: int
    difficulty: float | None     # 1.0-5.0
    would_take_again: float | None  # percentage (0-100)
    rmp_id: str | None
    
    @property
    def rmp_url(self) -> str | None:
        if self.rmp_id:
            return f"https://www.ratemyprofessors.com/professor/{self.rmp_id}"
        return None
    
    def to_dict(self) -> dict:
        return {
            "name": self.name,
            "rating": self.rating,
            "num_ratings": self.num_ratings,
            "difficulty": self.difficulty,
            "would_take_again": self.would_take_again,
            "rmp_url": self.rmp_url,
        }


class RMPCache:
    """Read-only cache for professor ratings."""
    
    def __init__(self):
        self._cache: dict[str, dict | None] = {}
        self._load_cache()
    
    def _load_cache(self) -> None:
        """Load ratings from JSON file."""
        if RATINGS_FILE.exists():
            with open(RATINGS_FILE) as f:
                self._cache = json.load(f)
            logger.info(f"Loaded {len(self._cache)} professor ratings from cache")
        else:
            logger.warning(f"RMP cache not found at {RATINGS_FILE}")
            logger.info("Run 'make refresh-rmp' to generate it")
    
    def _normalize_name(self, name: str) -> str:
        """Normalize professor name for cache lookup."""
        name = name.strip().lower()
        name = re.sub(r'\b(dr\.?|prof\.?|professor)\b', '', name, flags=re.IGNORECASE)
        if ',' in name:
            parts = name.split(',', 1)
            name = f"{parts[1].strip()} {parts[0].strip()}"
        return ' '.join(name.split())
    
    def get_rating(self, professor_name: str) -> ProfessorRating | None:
        """
        Get professor rating from cache.
        
        Returns None if professor not in cache or has no RMP profile.
        """
        if not professor_name:
            return None
        
        key = self._normalize_name(professor_name)
        
        # Skip TBA/Staff
        if key in ("tba", "staff", "-", ""):
            return None
        
        data = self._cache.get(key)
        if not data:
            return None
        
        return ProfessorRating(
            name=data["name"],
            rating=data.get("rating"),
            num_ratings=data.get("num_ratings", 0),
            difficulty=data.get("difficulty"),
            would_take_again=data.get("would_take_again"),
            rmp_id=data.get("rmp_id"),
        )
    
    def cache_stats(self) -> dict:
        """Get cache statistics."""
        total = len(self._cache)
        found = sum(1 for v in self._cache.values() if v is not None)
        return {
            "total_professors": total,
            "with_ratings": found,
            "without_ratings": total - found,
        }


# Global cache instance - loads on import
rmp_client = RMPCache()
